stages:
  - triggers

trigger-api:
  stage: triggers
  trigger:
    include: ".gitlab-ci-${PIPELINE_TYPE}-api.yml"
    strategy: depend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "develop"'
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "main"'
    - when: never

trigger-ui:
  stage: triggers
  trigger:
    include: ".gitlab-ci-${PIPELINE_TYPE}-ui.yml"
    strategy: depend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "develop"'
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "main"'
    - when: never

trigger-painel:
  stage: triggers
  trigger:
    include: ".gitlab-ci-${PIPELINE_TYPE}-painel.yml"
    strategy: depend
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "develop"'
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_REF_NAME == "main"'
    - when: never