"""add_municipio_id_paradas

Revision ID: a1df29eaf9c5
Revises: b4c8e2f7a1d3
Create Date: 2026-03-23 16:56:29.185955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1df29eaf9c5'
down_revision: Union[str, Sequence[str], None] = 'b4c8e2f7a1d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paradas_auto_linha', sa.Column('municipio_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_paradas_auto_linha_municipio_id'), 'paradas_auto_linha', ['municipio_id'], unique=False)
    op.create_foreign_key('fk_paradas_municipio_id', 'paradas_auto_linha', 'municipios', ['municipio_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_paradas_municipio_id', 'paradas_auto_linha', type_='foreignkey')
    op.drop_index(op.f('ix_paradas_auto_linha_municipio_id'), table_name='paradas_auto_linha')
    op.drop_column('paradas_auto_linha', 'municipio_id')
    # ### end Alembic commands ###
